# Generated by Django 5.0.3 on 2025-10-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founditem',
            options={'verbose_name_plural': 'Found Items'},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'verbose_name_plural': 'Lost Items'},
        ),
        migrations.AlterField(
            model_name='founditem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='found_photos/'),
        ),
    ]
