# Generated by Django 5.0.3 on 2025-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_founditem_options_alter_lostitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='photo',
            field=models.ImageField(default='found_photos/default.jpg', upload_to='found_photos/'),
            preserve_default=False,
        ),
    ]
